// Mocks generated by Mockito 5.4.6 from annotations
// in imdumb/test/features/movies_list/domain/use_cases/fetch_movies_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:imdumb/core/utils/exeptions/app_exceptions.dart' as _i5;
import 'package:imdumb/features/home/domain/entities/popular_movie_entity.dart'
    as _i6;
import 'package:imdumb/features/movies_list/domain/entities/movie_list_type.dart'
    as _i7;
import 'package:imdumb/features/movies_list/domain/repository/movies_list_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MoviesListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesListRepository extends _i1.Mock
    implements _i3.MoviesListRepository {
  MockMoviesListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppException, List<_i6.PopularMovieEntity>>>
  fetchMovies({
    required _i7.MovieListType? type,
    int? genreId,
    String? page = '1',
    String? language = 'es-ES',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovies, [], {
              #type: type,
              #genreId: genreId,
              #page: page,
              #language: language,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, List<_i6.PopularMovieEntity>>
                >.value(
                  _FakeEither_0<_i5.AppException, List<_i6.PopularMovieEntity>>(
                    this,
                    Invocation.method(#fetchMovies, [], {
                      #type: type,
                      #genreId: genreId,
                      #page: page,
                      #language: language,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.AppException, List<_i6.PopularMovieEntity>>
          >);
}
