// Mocks generated by Mockito 5.4.6 from annotations
// in imdumb/test/features/movie_detail/domain/use_cases/fetch_movie_detail_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:imdumb/core/utils/exeptions/app_exceptions.dart' as _i5;
import 'package:imdumb/features/movie_detail/domain/entities/cast_entity.dart'
    as _i8;
import 'package:imdumb/features/movie_detail/domain/entities/credit_detail_entity.dart'
    as _i9;
import 'package:imdumb/features/movie_detail/domain/entities/movie_detail_entity.dart'
    as _i6;
import 'package:imdumb/features/movie_detail/domain/entities/movie_image_entity.dart'
    as _i7;
import 'package:imdumb/features/movie_detail/domain/repository/movie_detail_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailRepository extends _i1.Mock
    implements _i3.MovieDetailRepository {
  MockMovieDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppException, _i6.MovieDetailEntity>>
  fetchMovieDetail({required int? movieId, String? language = 'es-ES'}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieDetail, [], {
              #movieId: movieId,
              #language: language,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, _i6.MovieDetailEntity>
                >.value(
                  _FakeEither_0<_i5.AppException, _i6.MovieDetailEntity>(
                    this,
                    Invocation.method(#fetchMovieDetail, [], {
                      #movieId: movieId,
                      #language: language,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, _i6.MovieDetailEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppException, List<_i7.MovieImageEntity>>>
  fetchMovieImages({required int? movieId}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieImages, [], {#movieId: movieId}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, List<_i7.MovieImageEntity>>
                >.value(
                  _FakeEither_0<_i5.AppException, List<_i7.MovieImageEntity>>(
                    this,
                    Invocation.method(#fetchMovieImages, [], {
                      #movieId: movieId,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.AppException, List<_i7.MovieImageEntity>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.AppException, List<_i8.CastEntity>>>
  fetchMovieCredits({required int? movieId, String? language = 'es-ES'}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieCredits, [], {
              #movieId: movieId,
              #language: language,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, List<_i8.CastEntity>>
                >.value(
                  _FakeEither_0<_i5.AppException, List<_i8.CastEntity>>(
                    this,
                    Invocation.method(#fetchMovieCredits, [], {
                      #movieId: movieId,
                      #language: language,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, List<_i8.CastEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppException, _i9.CreditDetailEntity>>
  fetchCreditDetail({required String? creditId, String? language = 'es-ES'}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCreditDetail, [], {
              #creditId: creditId,
              #language: language,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, _i9.CreditDetailEntity>
                >.value(
                  _FakeEither_0<_i5.AppException, _i9.CreditDetailEntity>(
                    this,
                    Invocation.method(#fetchCreditDetail, [], {
                      #creditId: creditId,
                      #language: language,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, _i9.CreditDetailEntity>>);
}
